export const manufacturers = [
  ["Acura", "אקורה"],
  ["Alfa Romeo", "אלפא רומאו"],
  ["Aston Martin", "אסטון מרטין"],
  ["Audi", "אאודי"],
  ["Bentley", "בנטלי"],
  ["BMW", "בי.אם.וו"],
  ["Buick", "ביואיק"],
  ["Cadillac", "קדילאק"],
  ["Chevrolet", "שברולט"],
  ["Chrysler", "קרייזלר"],
  ["Citroen", "סיטרואן"],
  ["Dodge", "דודג'"],
  ["Ferrari", "פרארי"],
  ["Fiat", "פיאט"],
  ["Ford", "פורד"],
  ["GMC", "ג'י.אם.סי"],
  ["Honda", "הונדה"],
  ["Hyundai", "היונדאי"],
  ["Infiniti", "אינפיניטי"],
  ["Jaguar", "יגואר"],
  ["Jeep", "ג'יפ"],
  ["Kia", "קיה"],
  ["Lamborghini", "למבורגיני"],
  ["Land Rover", "לנד רובר"],
  ["Lexus", "לקסוס"],
  ["Lincoln", "לינקולן"],
  ["Maserati", "מאזראטי"],
  ["Mazda", "מאזדה"],
  ["McLaren", "מקלארן"],
  ["Mercedes-Benz", "מרצדס-בנץ"],
  ["MINI", "מיני"],
  ["Mitsubishi", "מיצובישי"],
  ["Nissan", "ניסאן"],
  ["Porsche", "פורשה"],
  ["Ram", "ראם"],
  ["Rolls-Royce", "רולס-רויס"],
  ["Subaru", "סובארו"],
  ["Tesla", "טסלה"],
  ["Toyota", "טויוטה"],
  ["Volkswagen", "וולקסווגן"],
  ["Volvo", "וולוו"],
  ["Abarth", "אברת'"],
  ["Ariel", "אריאל"],
  ["Bugatti", "בוגאטי"],
  ["Caterham", "קאטרהאם"],
  ["Dacia", "דאצ'יה"],
  ["Foton", "פוטון"],
  ["Geely", "גילי"],
  ["Great Wall", "גרייט וול"],
  ["Haval", "הבאל"],
  ["Holden", "הולדן"],
  ["Hummer", "האמר"],
  ["Isuzu", "איסוזו"],
  ["Koenigsegg", "קוניגסג"],
  ["Lada", "לאדה"],
  ["Mahindra", "מהינדרה"],
  ["Maybach", "מייבאך"],
  ["Pagani", "פגאני"],
  ["Proton", "פרוטון"],
  ["Renault", "רנו"],
  ["Saab", "סאב"],
  ["SEAT", "סיאט"],
  ["Skoda", "סקודה"],
  ["Smart", "סמארט"],
  ["SsangYong", "סאניונג"],
  ["Tata", "טאטה"],
  ["Vauxhall", "ווקסהול"],
  ["Wuling", "וולינג"],
  ["Zotye", "זוטי"],
  ["BYD", "בי.וואי.די"],
  ["Chery", "צ'רי"],
  ["Daihatsu", "דייהטסו"],
  ["Datsun", "דטסון"],
  ["Dongfeng", "דונגפנג"],
  ["FAW", "אף.איי.דאבלי."],
  ["GAC", "גאק"],
  ["JAC", "ג'אק"],
  ["JMC", "ג'יי.אם.סי."],
  ["Lifan", "ליפאן"],
  ["Luxgen", "לוקסג'ן"],
  ["Maxus", "מקסוס"],
  ["Opel", "אופל"],
  ["Seres", "סרס"],
];




export const yearsOfProduction = [
  { title: "שנתון", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "הנעה",
    value: "",
  },
  {
    title: "דלק",
    value: "Gas",
  },
  {
    title: "חשמלי",
    value: "Electricity",
  },
  {
    title: "היברידי",
    value: "Hybrid",
  },
];

export const footerLinks = [
  {
    title: "אודות",
    links: [
      { title: "איך זה עובד", url: "/" },
      { title: "מומלצים", url: "/" },
      { title: "שׁוּתָפוּת", url: "/" },
      { title: "קשר עסקי", url: "/" },
    ],
  },
  {
    title: "חברה",
    links: [
      { title: "אירועים", url: "/" },
      { title: "בלוג", url: "/" },
      { title: "פודקאסט", url: "/" },
      { title: "הזמן חבר/ה", url: "/" },
    ],
  },
  {
    title: "חברתי",
    links: [
      { title: "דיסקורד", url: "/" },
      { title: "אינסטגרם", url: "/" },
      { title: "טוויטר", url: "/" },
      { title: "פייסבוק", url: "/" },
    ],
  },
];
